package com.syc.model.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * null
 * @TableName account
 */
@Data
public class Account implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-03-04 12:07:31
     */
    private Integer id;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 12:07:31
     */
    private String nickname;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 12:07:31
     */
    private String username;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 12:07:31
     */
    private String password;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 12:07:31
     */
    private String salt;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 12:07:31
     */
    private Integer status;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 12:07:31
     */
    private Date createat;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 12:07:31
     */
    private String ip;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 12:07:31
     */
    private String avatar;

    /**
     * 被赞次数
     *
     * @mbg.generated 2021-03-04 12:07:31
     */
    private Integer likecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbg.generated 2021-03-04 12:07:31
     */
    private static final long serialVersionUID = 1L;
}