package com.syc.model.entity;

import java.io.Serializable;
import lombok.Data;

/**
 * null
 * @TableName account_role
 */
@Data
public class AccountRoleKey implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-03-04 12:07:31
     */
    private Integer accountid;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 12:07:31
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account_role
     *
     * @mbg.generated 2021-03-04 12:07:31
     */
    private static final long serialVersionUID = 1L;
}