package com.syc.model.entity;

import java.io.Serializable;
import lombok.Data;

/**
 * null
 * @TableName auth_code
 */
@Data
public class AuthCode implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-03-04 12:07:31
     */
    private String id;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 12:07:31
     */
    private Integer accountid;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 12:07:31
     */
    private Long expireat;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 12:07:31
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auth_code
     *
     * @mbg.generated 2021-03-04 12:07:31
     */
    private static final long serialVersionUID = 1L;
}