package com.syc.model.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * null
 * @TableName login_log
 */
@Data
public class LoginLog implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-03-04 12:07:31
     */
    private Integer accountid;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 12:07:31
     */
    private Date loginat;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 12:07:31
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table login_log
     *
     * @mbg.generated 2021-03-04 12:07:31
     */
    private static final long serialVersionUID = 1L;
}