package com.syc.model.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * null
 * @TableName mo_account
 */
@Data
public class MoAccount implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-03-04 14:03:07
     */
    private Integer id;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 14:03:07
     */
    private String nickname;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 14:03:07
     */
    private String username;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 14:03:07
     */
    private String password;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 14:03:07
     */
    private String salt;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 14:03:07
     */
    private Integer status;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 14:03:07
     */
    private Date create_at;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 14:03:07
     */
    private String ip;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 14:03:07
     */
    private String avatar;

    /**
     * 被赞次数
     *
     * @mbg.generated 2021-03-04 14:03:07
     */
    private Integer like_count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mo_account
     *
     * @mbg.generated 2021-03-04 14:03:07
     */
    private static final long serialVersionUID = 1L;
}