package com.syc.model.entity;

import java.io.Serializable;
import lombok.Data;

/**
 * null
 * @TableName mo_auth_code
 */
@Data
public class MoAuthCode implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-03-04 14:03:07
     */
    private String id;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 14:03:07
     */
    private Integer account_id;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 14:03:07
     */
    private Long expire_at;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 14:03:07
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mo_auth_code
     *
     * @mbg.generated 2021-03-04 14:03:07
     */
    private static final long serialVersionUID = 1L;
}