package com.syc.model.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * 配置
 * @TableName mo_config
 */
@Data
public class MoConfig implements Serializable {
    /**
     * 配置key
     *
     * @mbg.generated 2021-03-04 14:03:07
     */
    private String key;

    /**
     * value
     *
     * @mbg.generated 2021-03-04 14:03:07
     */
    private String value;

    /**
     * 是否可用 0 否 1是
     *
     * @mbg.generated 2021-03-04 14:03:07
     */
    private Integer status;

    /**
     * 创建时间
     *
     * @mbg.generated 2021-03-04 14:03:07
     */
    private Date create_time;

    /**
     * 更新时间
     *
     * @mbg.generated 2021-03-04 14:03:07
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mo_config
     *
     * @mbg.generated 2021-03-04 14:03:07
     */
    private static final long serialVersionUID = 1L;
}