package com.syc.model.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * null
 * @TableName mo_login_log
 */
@Data
public class MoLoginLog implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-03-04 14:03:07
     */
    private Integer account_id;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 14:03:07
     */
    private Date login_at;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 14:03:07
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mo_login_log
     *
     * @mbg.generated 2021-03-04 14:03:07
     */
    private static final long serialVersionUID = 1L;
}