package com.syc.model.entity;

import lombok.Data;

import java.io.Serializable;

/**
 * null
 * @TableName mo_session
 */
@Data
public class MoSession implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-03-04 14:11:59
     */
    private String id;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 14:11:59
     */
    private Integer accountId;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 14:11:59
     */
    private Long expireAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mo_session
     *
     * @mbg.generated 2021-03-04 14:11:59
     */
    private static final long serialVersionUID = 1L;
}