package com.syc.model.entity;

import lombok.Data;

import java.io.Serializable;

/**
 * null
 * @TableName mo_sys_user_role
 */
@Data
public class MoSysUserRoleKey implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-03-04 14:11:59
     */
    private Integer userId;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 14:11:59
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mo_sys_user_role
     *
     * @mbg.generated 2021-03-04 14:11:59
     */
    private static final long serialVersionUID = 1L;
}