package com.syc.model.entity;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * null
 * @TableName mo_sys_user
 */
@Data
public class MoSysUser implements Serializable {
    /**
     * ID
     *
     * @mbg.generated 2021-03-04 14:11:59
     */
    private Integer id;

    /**
     * 用户名
     *
     * @mbg.generated 2021-03-04 14:11:59
     */
    private String username;

    /**
     * 密码
     *
     * @mbg.generated 2021-03-04 14:11:59
     */
    private String password;

    /**
     * 盐
     *
     * @mbg.generated 2021-03-04 14:11:59
     */
    private String salt;

    /**
     * 状态 0-禁用 1-正常
     *
     * @mbg.generated 2021-03-04 14:11:59
     */
    private Integer status;

    /**
     * IP
     *
     * @mbg.generated 2021-03-04 14:11:59
     */
    private String ip;

    /**
     * 头像
     *
     * @mbg.generated 2021-03-04 14:11:59
     */
    private String avatar;

    /**
     * 注册时间
     *
     * @mbg.generated 2021-03-04 14:11:59
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mo_sys_user
     *
     * @mbg.generated 2021-03-04 14:11:59
     */
    private static final long serialVersionUID = 1L;
}