package com.syc.model.entity;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * null
 * @TableName mo_sys_role
 */
@Data
public class MoSysRole implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-03-04 14:11:59
     */
    private Integer id;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 14:11:59
     */
    private String name;

    /**
     * 
     *
     * @mbg.generated 2021-03-04 14:11:59
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mo_sys_role
     *
     * @mbg.generated 2021-03-04 14:11:59
     */
    private static final long serialVersionUID = 1L;
}