server:
  port: 9090

spring:
  application:
    name: morning
  profiles:
    active: @profiles.active@
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages

# 日志配置
logging:
  level:
    com.syc: debug
    org.springframework: warn