server:
  port: 9090

spring:
  application:
    name: morning
  profiles:
    active: @profiles.active@
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
# 日志配置
logging:
  level:
    com.syc: debug
    org.springframework: warn

morning:
  sequence:
    snowflake:
      dataCenterId: 1
      workerId: 3
      enableThread: false